revaniputeri/final-project-group-3

documents/project-charter.md
Project Charter ( Kurang Milestone Timeline)
=> feat : update project charter

app/public/index.php
Home page within the dashboard:
1. Achievement showcase (show the top achievement)
2. Progress tracking (through graphs / charts)
=> Syafa home

app/public/index.php
Achievement Submission:
1. Submission form
2. Achievement history
3. Info
=> Syaf achievement

app/public/index.php
Submission Form:
1. Prestasi akademik
2. Prestasi non akademik
=> Syafa submission

app/public/index.php
Info page within achievement submission:
1. Point prestasi
2. Reward
=> Syafa info

app/src/Controllers/AchievementController.php
This pull request introduces the `AchievementController` which includes methods for handling various submission processes. 
- A new `AchievementController` has been implemented to manage achievement submissions effectively.
- The controller includes necessary methods to process and validate submissions.
Please review the code and provide feedback or approve if all looks good!
=> 🎉 feat: add AchievementController with submission methods

app/public/index.php
This pull request introduces the achievement submission and leaderboard routes to enhance the functionality of our application. The new features allow users to submit their achievements and view the corresponding leaderboard, promoting user engagement and competition.
- Implemented routes for submitting achievements.
- Developed the leaderboard functionality to display user rankings based on submitted achievements.
These enhancements aim to improve user experience by fostering a sense of accomplishment and motivating users to engage more with the platform.
=> ✨ feat: add achievement submission and leaderboard routes

app/src/Controllers/IndexController.php
This pull request addresses a minor formatting issue by adding a newline at the end of the `IndexController.php` file. This change ensures that the file adheres to coding standards that prefer files to end with a newline, improving compatibility with various tools and editors.
- Added a newline character at the end of `IndexController.php`.
No functional changes have been introduced; this is purely a formatting improvement.
=> 🚧 fix: add a newline at the end of IndexController.php

app/src/Controllers/AchievementController.php, app/src/Models/Achievement.php
This PR introduces the `Achievement` model, which enhances the application's capability to manage and validate achievements effectively.
- **New Feature**: The `Achievement` model has been added, featuring robust file validation processes and database interaction methods. This ensures that achievements can be added and managed seamlessly.
- **Improvements**: Refactored the achievement submission and history logic, which now includes improved error handling and optimized date processing. This makes the submission process more reliable and user-friendly.
Feel free to review the changes and provide feedback. Thank you!
=> reva-achievement

app/src/Views/achievement-submission.php, app/src/Views/achievements.php
✨ feat: update achievement link and add submission form
This pull request introduces updates to the achievement link and implements a new submission form feature. 
- The achievement link has been updated to direct users to the most relevant resources.
- A new submission form has been added to enhance user interaction and facilitate easier submissions.
These changes aim to improve user experience by providing clearer access to achievements and streamline the submission process.
Consider any potential impact on existing features and test the form functionality to ensure seamless integration.
=> ✨ feat: update achievement link and add submission form

app/public/index.php, app/src/Controllers/AchievementController.php, app/src/Models/Achievement.php, app/src/Utils/FileUpload.php
✨ refactor: update achievement submission paths and methods
This pull request refactors the achievement submission functionality by updating the existing paths and methods involved in the process. The aim of this change is to enhance code readability and maintainability while ensuring that the submission flow remains intact.
- Updated paths related to achievement submission to align with the latest application structure.
- Refactored methods to improve performance and clarity.
No breaking changes have been introduced, and all existing tests pass successfully. This change will facilitate future improvements and optimizations in the achievement submission process.
=> ✨ refactor: update achievement submission paths and methods

app/schema/seedAchievement.php, app/schema/seedLecturer.php, app/schema/seedStudent.php
**Title:** ✨ feat: add data seeding for students, lecturer, and achievements
**Description:**
This pull request introduces data seeding functionality for the application, specifically targeting the creation of initial datasets for students, lecturers, and achievements. The new feature aims to streamline the setup process for development and testing environments by providing relevant and realistic data.
**Changes Made:**
- Implemented a seeding script that populates the database with sample students, lecturers, and achievement records.
These additions will enhance our testing capabilities and provide a better developmental experience by mirroring the expected data structure in the application.
=> ✨ feat: add data seeding for students, lecturer, and achievements

app/src/App/Router.php, app/src/Controllers/AuthController.php, app/src/Middleware/AuthMiddleware.php, app/src/Views/login.php
This pull request introduces the implementation of authentication middleware and enhanced error handling within the application. 
- Implemented authentication middleware to manage user access and enforce security protocols.
- Enhanced error handling mechanisms to provide clearer feedback and improve overall user experience.
These updates aim to streamline user authentication processes and ensure the application handles errors more gracefully. Feel free to review and provide feedback!
=> 🎉 feat: implement authentication middleware and error handling

app/src/Models/User.php
**Title:** 👷‍♂️ feat: refactor User model methods and add fromArray method
**Summary:**
This pull request introduces a refactor of the User model methods, enhancing code clarity and maintainability. In addition, a new `fromArray` method has been added to facilitate the creation of User objects from array data, improving our data handling capabilities.
**Changes Made:**
- Refactored existing methods in the User model for improved readability and performance.
- Implemented the `fromArray` method to streamline object instantiation using array data.
This enhancement aims to optimize our user management processes and ensure that our User model remains efficient and easy to work with.
=> 👷‍♂️ feat: refactor User model methods and add fromArray method

app/schema/create.sql, app/schema/seedAchievement.php, app/schema/seedLecturer.php, app/schema/seedStudent.php
This pull request focuses on enhancing the `reva-schema` by making updates to ensure consistency and clarity in the data types used throughout the schema.
- **Schema Updates**: 
- Updated various data types to improve clarity and consistency across the schema. This change aims to streamline data handling and reduce confusion regarding type usage. 
- **Seed Data Logic Refactor**: 
- Refactored the seed data generation logic to leverage enums for better maintainability and readability. This improvement will facilitate easier updates to the seed data in the future and enhance the overall integrity of the data.
- ✨ fix: update data types for consistency and clarity in schema
- ✨ refactor: update seed data generation logic to use enums
=> reva-schema

app/schema/create.sql, app/schema/drop.sql
This pull request introduces a refactor of the database schema by restructuring foreign key constraints and dropping unnecessary tables. The changes aim to improve the overall integrity and performance of our database.
- **Restructured Foreign Key Constraints**: The relationships between tables have been revisited and optimized to enhance data integrity and reduce redundancy.
- **Dropped Unused Tables**: Tables that are no longer in use have been removed from the schema, streamlining our database and improving maintainability.
This restructuring paves the way for better data management and prepares our database for future feature development. Please review the changes and provide feedback as necessary.
=> ✨ chore: restructure foreign key constraints and drop tables

app/public/index.php, app/src/Controllers/AchievementController.php, app/src/Models/Achievement.php, app/src/Models/Admin.php, app/src/Models/Dosen.php, app/src/Models/Student.php, app/src/Views/achievement-submission.php
**Pull Request Description:**
This pull request implements the addition of profile update and validation processes specifically for achievements. 
- Introduced functionality that allows users to update their profiles with new achievement-related information.
- Implemented validation processes to ensure the integrity and correctness of the updated achievement data.
These enhancements aim to improve user engagement and experience by allowing seamless management of achievements within user profiles.
Please review the changes and provide your feedback. Thank you!
=> ✨ feat: add profile update and validation processes for achievement

app/src/Views/register.php
=> Alvi register

app/public/assets/js/achievement-edit.js, app/public/index.php, app/src/Controllers/AchievementController.php, app/src/Controllers/AssetsController.php, app/src/Controllers/IndexController.php, app/src/Models/Achievement.php, app/src/Views/achievement-edit.php
This PR introduces new features focused on enhancing the application’s capabilities. 
**Features Added:**
- Implementation of file serving functionality that allows users to upload and access files seamlessly.
- New routes for editing achievements, which streamline user interactions and enable better management of achievement records.
These enhancements aim to improve user experience and add valuable functionalities to the application. Please review the changes and provide feedback.
=> feat: add file serving functionality and achievement editing routes

app/public/assets/js/achievement-submission.js, app/src/Controllers/AchievementController.php, app/src/Models/Achievement.php, app/src/Views/achievement-edit.php, app/src/Views/achievement-submission.php
**Title:** Fix: Update File Validation and Refactor Selection Logic
**Summary:**
This pull request addresses issues related to file validation processes and refactors the selection logic to enhance code readability and maintainability. 
**Changes Made:**
- Improved file validation to ensure that only acceptable file types are processed.
- Refactored selection logic for better clarity and efficiency in how files are selected for processing.
These changes aim to improve the overall functionality of the application while adhering to coding best practices. Please review the modifications and provide feedback.
=> fix: update file validation and refactor selection logic

app/src/Controllers/IndexController.php, app/src/Views/dashboard.php
This pull request focuses on refactoring the code by removing the `getTopAchievements` method along with any associated debug output. This change aims to streamline the codebase and enhance readability by eliminating unused functionality and unnecessary logs. 
Key Changes:
- Removed the `getTopAchievements` method.
- Eliminated debug output related to the removed method.
These changes will help improve the maintainability of the code and allow for more efficient future development.
=> refactor: remove getTopAchievements method and debug output

app/public/assets/js/achievement-submission.js, app/src/Views/achievement-edit.php
**Title:** Fix Button Add Supervisor and Students
**Summary:**  
This pull request addresses an issue with the button functionality for adding supervisors and students. The previous implementation was not working as intended, causing frustration for users trying to add new entries.
**Changes Made:**  
- Fixed the button for adding supervisors and students to ensure it operates correctly. 
**Impact:**  
Users will now be able to add supervisors and students seamlessly, improving the overall experience of the application.
Please review the changes and provide any necessary feedback. Thank you!
=> fix: fix button add supervisor and students

app/public/assets/js/achievement-submission.js, app/src/Views/achievement-edit.php, app/src/Views/achievement-submission.php
This pull request addresses issues related to the loading of the Select2 script and improves the validation process for team data.
- Updated the method of loading the Select2 script to ensure it is loaded correctly.
- Enhanced validation logic for team inputs to improve data integrity and user experience.
These changes are aimed at providing better functionality and robustness to the application, ensuring that team data is validated more effectively and that the Select2 component performs reliably.
=> fix: update select2 script loading and enhance team validation

app/public/assets/js/template.js, app/src/Views/dashboard-admin.php, app/src/Views/dashboard.php, app/src/Views/partials/navbar.php, app/src/Views/partials/sidebar-student.php
This pull request introduces updates to the achievement titles and their respective links within the application. The changes aim to enhance clarity and ensure users can easily understand the purpose of each achievement.
- Updated the wording of various achievement titles for better clarity.
- Revised links to point to the most relevant resources, improving user experience and navigation.
These enhancements are expected to make it easier for users to engage with achievements, thereby improving overall interaction with the platform. Please review the modifications and provide feedback.
=> feat: update achievement titles and links for clarity

app/src/Views/achievement-edit.php, app/src/Views/achievement-history-admin.php, app/src/Views/achievement-history.php, app/src/Views/achievement-submission.php
This pull request proposes a refactor of the application layout to incorporate a sidebar and a navbar. The changes aim to enhance the user interface and improve navigation throughout the application.
- Updated the layout structure to include a sidebar for quick access to various sections.
- Introduced a navbar for better navigation options and responsiveness.
The goal of this refactor is to provide a more organized and user-friendly experience, helping users to navigate the application efficiently.
No functional features were added or removed in this commit; the changes are primarily focused on layout improvements. Further enhancements and features can build upon this new structure.
=> refactor: update layout with sidebar and navbar includes

app/src/Controllers/AuthController.php, app/src/Controllers/IndexController.php, app/src/Models/Achievement.php, app/src/Views/dashboard-admin.php, app/src/Views/dashboard.php, app/src/Views/partials/sidebar-admin.php
**Pull Request Description:**
This pull request enhances the admin dashboard layout and styles to improve overall usability and aesthetic appeal. The modifications include updated visual elements and a restructured layout to streamline user experience. 
- Enhanced visuals of the admin dashboard.
- Improved layout for better navigation and accessibility.
These improvements aim to provide a more intuitive interface for administrators, making it easier to manage tasks and access critical information.
=> feat(dashboard): enhance admin dashboard layout and styles

app/public/assets/js/achievement-submission.js, app/src/Controllers/AchievementController.php, app/src/Views/achievement-submission.php
**Title:** feat: pre-fill form fields with existing data for submission
**Summary:**
This pull request introduces a feature that automatically pre-fills form fields with existing data during the submission process. This enhancement is designed to improve user experience by reducing the need for users to manually input previously entered information, thereby streamlining the submission workflow.
**Commit Details:**
- Implemented functionality to pre-fill form fields with existing user data.
- Ensured compatibility with existing form submission logic.
**Impact:**
This feature is expected to boost efficiency and user satisfaction, as users will find it easier to complete forms with relevant preloaded information.
Please review the changes and provide feedback!
=> feat: pre-fill form fields with existing data for submission

app/config.php, app/src/App/Connection.php, app/src/Controllers/AuthController.php, app/src/Middleware/AuthMiddleware.php, app/src/Views/login.php
This pull request introduces a significant enhancement to the authentication and database connection handling mechanisms within the application. The primary goal of this refactor is to improve both the performance and security of the system while ensuring a seamless user experience.
Key Changes:
- Streamlined authentication processes for quicker user login and registration.
- Enhanced database connection handling to ensure more reliable connections and better error management.
- Improved code organization for better readability and maintainability.
By implementing these changes, we aim to provide a more robust and efficient system for our users while adhering to best practices in security and performance.
=> refactor: improve authentication and database connection handling
